### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by burtonageo** [PistonDevelopers/gfx_graphics#103]
When compiling the latest gfx_graphics, there is a compile error:

    src/g2d.rs:275:26: 275:32 error: unresolved import `gfx::state::Normal`. There is no `Normal` in `gfx::state`
    src/g2d.rs:275         use gfx::state::{Normal, Inverse, Factor};
                                            ^~~~~~
    src/g2d.rs:275:34: 275:41 error: unresolved import `gfx::state::Inverse`. There is no `Inverse` in `gfx::state`
    src/g2d.rs:275         use gfx::state::{Normal, Inverse, Factor};
                                                    ^~~~~~~

**Comment by bvssvni** [comment]
This should now be fixed.
