### ISSUE TITLE
Upgrade G2D and GraphicsBackEnd to latest gfx

### ISSUE THREAD

**Issue by Potpourri** [PistonDevelopers/gfx_graphics#139]
I have a problems with this.
The main problem is `ParamsUV`. `TextureParam` now has type parameter and if I pass `GlResources`, then can't create `ParamsUV` using `D: Device`, but and generic type doesn't work, `#[shader_param()]` can't implement `ShaderParam` to generic type.
@kvark need help

**Comment by bvssvni** [comment]
I think this should also be opened up as an issue on Gfx.

**Comment by kvark** [comment]
https://github.com/gfx-rs/gfx-rs/issues/606

You could still write the code in a more or less generic fashion, you'll just need some `where` clauses to match `D::Resources == GlResources`. Sorry for the inconvenience!

Meanwhile, we are working on improving `ShaderParam`. Stay tuned.

**Comment by bvssvni** [comment]
I go the example working, but now it depends on gfx_device_gl. This is good enough for now.

**Comment by kvark** [comment]
Awesome!

**Comment by Potpourri** [comment]
Ok, thank you all, I think it can be closed now.
