### ISSUE TITLE
Add example to test draw state

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/gfx_graphics#159]
Can copy the imagetest example.

**Comment by bvssvni** [comment]
I'm hitting an ICE:

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'arithmetic operation overflowed', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libsyntax/codemap.rs:73
```

**Comment by bvssvni** [comment]
Oh, there is an issue for this already https://github.com/rust-lang/rust/issues/23407

**Comment by bvssvni** [comment]
Still a problem on `rustc 1.0.0-nightly (ea8b82e90 2015-03-17) (built 2015-03-18)`

**Comment by Potpourri** [comment]
Fix already in master, left to wait next nightly.

**Comment by Potpourri** [comment]
Fix already in current nightly: `rustc 1.0.0-nightly (f4e0ce66a 2015-03-19) (built 2015-03-20)`.

**Comment by bvssvni** [comment]
- [ ] Additive blending (normal)
- [ ] Multiplicative blending
- [ ] Clip image to inside ellipse using stencil buffer

**Comment by bvssvni** [comment]
Done.
