### ISSUE TITLE
Fix image_test to properly create the main framebuffer

### ISSUE THREAD

**Issue by kvark** [PistonDevelopers/gfx_graphics#203]
Since it's using SDL, and we don't have any SDL integration at the moment, we can use the [fake output](https://github.com/gfx-rs/gfx_device_gl/blob/master/src/factory.rs#L125).

**Comment by Potpourri** [comment]
Ohh, I already fixed it...

**Comment by kvark** [comment]
mmm

**Comment by kvark** [comment]
I wish you were on IRC more often to sync this things

**Comment by Potpourri** [comment]
Yes, you are right, I need begin use IRC.

**Comment by kvark** [comment]
@Potpourri to be fair though, I don't like IRC myself. How about this - I make a Gitter room for Piston and you hang out there?

**Comment by Potpourri** [comment]
Yeah, of course. Gitter will be great.
