### ISSUE TITLE
Bugfix GlyphCache

### ISSUE THREAD

**Issue by Potpourri** [PistonDevelopers/gfx_graphics#205]
Currently, `GlyphCache` has several bugs(panic when trying create glyph for space; if several the same chars follow each other, then will be drawn only one; and others). Now I'm working to fix it.

**Comment by mitchmindtree** [comment]
@Potpourri, eddyb mentioned he fixed a similar issue by calling [GlyphCache's update method](https://github.com/PistonDevelopers/gfx_graphics/blob/master/src/glyph.rs#L71-L72) (here is a [pic of it working](https://i.imgur.com/x4yFAKA.png)) - does this fix your problem also?

**Comment by Potpourri** [comment]
@mitchmindtree no, bugs which I mentioned, are within realization GlyphCache.

**Comment by kvark** [comment]
Thanks @Potpourri ! Let me know if you need any help with it.
