### ISSUE TITLE
Simplify GfxGraphics<> generic parameters

### ISSUE THREAD

**Issue by kvark** [PistonDevelopers/gfx_graphics#209]
Perhaps, we could just have `GfxGraphics<'a, Device, Output>`?

cc @eddyb

**Comment by bvssvni** [comment]
How does this affect multi-thread rendering?

**Comment by kvark** [comment]
It wouldn't affect multi-threading. We just need simpler generic parameters for this thing.

**Comment by bvssvni** [comment]
Maybe we could use `gfx::Stream` here? Perhaps we should wait until that part of Gfx has settled.

**Comment by kvark** [comment]
It should use the `Stream`, absolutely.

**Comment by bvssvni** [comment]
This issue is outdated. Closing.
