### ISSUE TITLE
Stencil clipping not working

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/gfx_graphics#225]
In the "draw_state_test" example I am trying to render an ellipse to the stencil buffer and then clip an image using the stencil buffer. The function `graphics::clip_draw_state()` should give a draw state that disables color output and writes to the stencil buffer, and the function `graphics::inside_draw_state()` should give a draw state that tests for the value rendered by `clip_draw_state` and renders only fragments for that value.

```Rust
let transform = c.transform.trans(200.0, 200.0);
Ellipse::new([1.0, 0.0, 0.0, 1.0])
    .draw([0.0, 0.0, 50.0, 50.0], clip_draw_state(), transform, g);
Image::new().draw(&rust_logo, inside_draw_state(), transform, g);
```

**Comment by bvssvni** [comment]
Seems that `gfx::Output::get_stencil` returns `None` by default and this is not implemented by `gfx_device_gl::Output`.

**Comment by kvark** [comment]
It is supposed to return `None` for all the surfaces, actually. One should use `Output::get_mask` to query available surfaces for the main frame.

**Comment by kvark** [comment]
Question is - why do you even call `get_stencil`?

**Comment by bvssvni** [comment]
https://github.com/gfx-rs/gfx_device_gl/blob/7677733ae7d0e977354a2c9b48f787a226d481da/src/factory.rs#L64 Stencil buffer seems to be enabled here.

**Comment by kvark** [comment]
I'll need to debug your test to see what GL thinks we are doing. It would help if you provide an apitrace capture.

**Comment by bvssvni** [comment]
@kvark Do you get any clipping when running `draw_state_test`?

**Comment by kvark** [comment]
Sorry, I intended to, but haven't managed to run it yet.

**Comment by bvssvni** [comment]
https://gist.github.com/bvssvni/c5d43f69bbf80f8370de

**Comment by kvark** [comment]
First problem that I see - you are not clearing the stencil.

**Comment by kvark** [comment]
Another problem is - I don't see sdl2_window [requesting](https://github.com/PistonDevelopers/sdl2_window/blob/master/src/lib.rs#L49) stencil at all. This is what implementing `Window` for it is needed for - to know which surfaces are really given. Perhaps, you could try using glutin to see if it changes anything?

**Comment by bvssvni** [comment]
It works with Glutin. I opened https://github.com/PistonDevelopers/sdl2_window/issues/168

**Comment by bvssvni** [comment]
Test with SDL2/Glutin/GLFW. It works!

Closing.

**Comment by kvark** [comment]
Awesome!
