### ISSUE TITLE
Should Gfx2d::draw take FnOnce instead of FnMut?

### ISSUE THREAD

**Issue by mystal** [PistonDevelopers/gfx_graphics#227]
Currently, `Gfx2d::draw` takes `FnMut` as the type for the closure it calls. Given that the closure is used only once, I think its type can be changed to `FnOnce`. This would be strictly more flexible, since both `Fn` and `FnMut` implement `FnOnce`.

I have a specific case where I want to pass in a closure that moves some values into it from its parent scope, which requires `FnOnce`. However, the `FnMut` requirement prevents me from doing so.

**Comment by bvssvni** [comment]
I think you are right.
