### ISSUE TITLE
offset and size are completely ignored when constructing a Character

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/gfx_graphics#229]
See [here](https://github.com/PistonDevelopers/gfx_graphics/blob/master/src/glyph.rs#L104) for the magic numbers. It should be implemented like `opengl_graphics`' glyph cache ([here](https://github.com/PistonDevelopers/opengl_graphics/blob/master/src/glyph_cache.rs#L84)).

**Comment by Potpourri** [comment]
Character constructing in `update` [code](https://github.com/PistonDevelopers/gfx_graphics/blob/master/src/glyph.rs#L69-L76).

**Comment by mitchmindtree** [comment]
@Potpourri just curious, why is it in a separate `update` method?

We should only have to construct the character that's requested if it doesn't exist *when* it is requested. Currently instead, `need_update` is set to true and in turn every pre-existing character in the whole cache has to be updated, even if there's only one extra character.

**Comment by mitchmindtree** [comment]
Ahh sorry, I see you check for an empty_texture first. Still, an `update` method shouldn't be necessary if we just construct it when requested.

**Comment by mitchmindtree** [comment]
Ahh, you need a Factory to construct the Texture. Closing

**Comment by kvark** [comment]
@mitchmindtree yes. It could be solved by having a separate factory in the gfx_graphics (https://github.com/gfx-rs/gfx-rs/issues/690), or by moving the main factory into it.
