### ISSUE TITLE
Does not build on gfx 0.5

### ISSUE THREAD

**Issue by LaylConway** [PistonDevelopers/gfx_graphics#234]
The latest gfx update breaks this library.

**Comment by csherratt** [comment]
Are you taking a look at this @LaylConway?

**Comment by LaylConway** [comment]
I am but it will probably take me longer than someone else to fix it.

**Comment by LaylConway** [comment]
I'm feeling like I don't have the experience with gfx to make my fork of gfx_graphics work within a decent time frame, so don't count on me getting it done any time soon.

**Comment by LaylConway** [comment]
Should have been fixed by #235
