### ISSUE TITLE
Update to gfx 0.6 (what to do now OwnedBatch is gone?)

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/gfx_graphics#244]
I've not worked on the innards of gfx_graphics before and I'm not sure how to update it to the latest gfx 0.6 changes and the removal of OwnedBatch?

Any help appreciated! @bvssvni @kvark

**Comment by Kagami** [comment]
Seems like `OwnedBatch` was just renamed to `Full`: https://github.com/gfx-rs/gfx-rs/pull/759/files#diff-9727ac41ee298b338aa97b20cd10c264L101

**Comment by mitchmindtree** [comment]
:blush: thanks @Kagami, I've got it building now, will do a PR shortly :+1:
