### ISSUE TITLE
Switch from freetype-rs to rusttype (or provide it as an alternative)

### ISSUE THREAD

**Issue by StelarCF** [PistonDevelopers/gfx_graphics#276]
FreeType as a dependency makes it harder to port to other platforms, especially when trying to cross-compile from linux. FreeType is not likely to change that much, so using a statically compiled alternative will make it easier to compile.

Perhaps the option to use Freetype as an alternative should be provided, but I think using RustType (once it matures enough, if it isn't mature enough already) will benefit cross-platform development.

**Comment by bvssvni** [comment]
There is also https://github.com/pistondevelopers/truetype.

**Comment by kvark** [comment]
And also https://github.com/PistonDevelopers/gfx_text/issues/38
I don't know which one of {truetype, rusttype} is better, but at least one of them should beat freetype-rs eventually.

**Comment by bvssvni** [comment]
I opened up an issue for discussion https://github.com/PistonDevelopers/truetype/issues/25, and informed the author of RustType. Hope we can get our heads together and come up with a good plan.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/gfx_graphics/pull/288
