### ISSUE TITLE
Improve performance for colored graphics

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/gfx_graphics#283]
The deform example is noticeable slower in https://github.com/PistonDevelopers/piston-examples/pull/333 when turning on the grid. Likely causing a bottleneck in Conrod too.

**Comment by bvssvni** [comment]
The key here is to not call `encoder.draw` more than necessary. All sequential rendering with colored graphics should result in as few draw calls as possible.

- [ ] Change shaders in [piston-shaders_graphics2d](https://github.com/PistonDevelopers/shaders/tree/master/graphics2d) to use colors per vertex instead of uniform
- [ ] Add an offset counter that increases when appending new triangles
- [ ] Add a method to `GfxGraphics` for flushing data for rendering
- [ ] Flush data when offset counter is closer to buffer length minus `BUFFER_SIZE`, the size of chunks sent from piston-graphics. This avoids splitting chunks across draw calls.
- [ ] Flush data in `Gfx2d::draw`

**Comment by mitchmindtree** [comment]
Nice! I'm looking forward to seeing what comes of this :smile:

**Comment by kvark** [comment]
Don't forget to track the numbers (milliseconds per frame) when optimizing
