### ISSUE TITLE
Convert color to sRGB when drawing glyph

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/gfx_graphics#290]
See https://github.com/PistonDevelopers/gfx_graphics/pull/288#issuecomment-204077852

Not sure if this is correct yet, but might be worth checking to see if it fixes the blurring.

https://github.com/PistonDevelopers/gfx_graphics/blob/master/src/glyph.rs#L110

Could copy code from https://github.com/PistonDevelopers/graphics/blob/master/src/color.rs#L62-L69

**Comment by gaborigloi** [comment]
The OpenGL wiki says that alpha values are always linear: https://www.opengl.org/wiki/Image_Format#sRGB_colorspace.
This is why I think the current character cache in glium_graphics is correct, even though it draws the glyph to a sRGB texture: https://github.com/PistonDevelopers/glium_graphics/blob/master/src/glyph_cache.rs#L58.
The texture values will be interpreted as sRGB, and converted to linear RGB when sampled, but we only use the alpha channel there.

**Comment by kvark** [comment]
Yes, as @gaborigloi said, if you only care about the alpha, than sRGB makes no difference.

**Comment by bvssvni** [comment]
Closing.
